name: vRO CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  vro:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      # 1) Checkout
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2) Node (bez cache → nie wymagamy lock‑file)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3) Instalacja zależności (npm install, bo brak lock‑file)
      - name: Install deps
        run: npm install

      # ---------- LINT ----------
      - name: Extract & lint vRO scripts
        run: node scripts/lint-workflows.js
