name: vRO CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  vro:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      # ---------- LINT ----------
      - name: Extract & lint vRO scripts
        run: node scripts/lint-workflows.js

