name: vRO CI

on:
  pull_request:


jobs:
  vro:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      # 1) Checkout
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2) Node (bez cache → nie wymagamy lock‑file)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3) Instalacja zależności (npm install, bo brak lock‑file)
      - name: Install deps
        run: npm install

      # ---------- LINT ----------
      - name: Extract & lint vRO scripts
        run: node scripts/lint-workflow.js

      - name: Validate vRO variables & descriptions
        run: node scripts/validate-workflow.js
